version: '3.7'

services:
  vault:    
    environment: 
      - VAULT_DEV_ROOT_TOKEN_ID=secret

  seq:
    ports: 
      - "5341:5341"

  postgres.data:
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=P@ssw0rd

  keycloak:
    environment:
      - KEYCLOAK_USER=lab
      - KEYCLOAK_PASSWORD=P@ssw0rd
      - DB_ADDR=postgres.data
      - DB_USER=lab
      - DB_PASSWORD=P@ssw0rd
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak

